os: osx
osx_image: xcode14.2
language: objective-c

env:
  matrix:
    - TEST_SDK=iphonesimulator12.1 OS=12.1 NAME='iPhone XR'
    - TEST_SDK=iphonesimulator12.1 OS=12.1 NAME='iPhone 7'

script:
  - swift build
  - swift test
  - set -o pipefail test -enableCodeCoverage YES

after_success:
  - curl -Os https://uploader.codecov.io/latest/macos/codecov chmod +x codecov ./.build/arm64-apple-macosx/debug/SwiftDependencyInjector.json