os: osx
osx_image: xcode14.2
language: objective-c

script:
  - swift build
  - swift test --enable-code-coverage
  - set -o pipefail test -enableCodeCoverage YES

after_success:
  - bash <(curl -s https://codecov.io/bash) -t {CODECOV_TOKEN}
